IMPORT JAVA.IO.BUFFEREDREADER;
IMPORT JAVA.IO.FILEREADER;
IMPORT JAVA.IO.IOEXCEPTION;
IMPORT JAVA.UTIL.REGEX.MATCHER;
IMPORT JAVA.UTIL.REGEX.PATTERN;

	PUBLIC STATIC VOID MAIN(STRING[] ARGS) THROWS IOEXCEPTION {

		TRY (BUFFEREDREADER BR = NEW BUFFEREDREADER(NEW FILEREADER(
				"SUBTASK4IO.JAVA"))) {
			STRINGBUILDER SB = NEW STRINGBUILDER();
			STRING CODE = BR.READLINE();
			WHILE (CODE != NULL) {
				INT LAST = 0;
				MATCHER m = PATTERN.COMPILE("(?U)(\\w{2,})").MATCHER(CODE);
				WHILE (m.FIND()) {
					SB.APPEND(CODE.SUBSTRING(LAST, m.START()));
					SB.APPEND(m.GROUP(0).TOUPPERCASE());
					LAST = m.END();
				}
				SB.APPEND(CODE.SUBSTRING(LAST));
				SB.APPEND(SYSTEM.LINESEPARATOR());
				CODE = BR.READLINE();
			}
			CODE = SB.TOSTRING();
			SYSTEM.OUT.PRINTLN(CODE);
			WRITE("SUBTASK4IO.JAVA", "CODE");
		}

	}
